knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:
            page-size: A4
            margin-top: 10mm
            margin-right: 10mm
            margin-bottom: 10mm
            margin-left: 10mm
            encoding: utf-8