# config/packages/reset_password.yaml
symfonycasts_reset_password:
  request_password_repository: App\Repository\ResetPasswordRequestRepository
  lifetime: 3600  # 1 heure
  throttle_limit: 3600  # 1 heure entre chaque demande
  enable_garbage_collection: true  # Nettoie les tokens expir√©s automatiquement