parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TranslationService:
        arguments:
            $googleTranslateApiKey: '%env(GOOGLE_TRANSLATE_API_KEY)%'

    App\Service\PdfService:
        arguments:
            $pdf: '@knp_snappy.pdf'

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $twig: '@twig'

    App\Service\ModerationService:
        arguments:
            $twilioSid: '%env(TWILIO_SID)%'
            $twilioToken: '%env(TWILIO_TOKEN)%'
            $twilioPhone: '%env(TWILIO_PHONE)%'
            $adminPhone: '%env(ADMIN_PHONE)%'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%kernel.project_dir%/public/uploads'

    App\Service\ChatbotService:
        arguments:
            $httpClient: '@http_client'
            $huggingfaceApiKey: '%env(HUGGINGFACE_API_KEY)%'
            $openaiApiKey: '%env(OPENAI_API_KEY)%'
            $openrouterApiKey: '%env(OPENROUTER_API_KEY)%'